FROM node:18-alpine
WORKDIR /app

# Install dependencies
COPY package*.json ./
RUN npm install --legacy-peer-deps

# Copy project files
COPY . .

ENV PORT=3000
EXPOSE 3000

CMD ["npm","run","dev","--","-H","0.0.0.0"]
